### ISSUE TITLE
[Feature]: Remove upper bound on python version

### ISSUE THREAD

**Issue by nat-n** [rstcheck/rstcheck#171]
### To Dos

- [X] I have checked the [issues](https://github.com/rstcheck/rstcheck/issues) and think that this is not a duplicate.

- [X] I added a very descriptive title to this issue.

### Description

Currently rstcheck declares compatibility with python versions `>=3.7 <4.0`. This can be problematic, particularly because it makes it difficult to use recent versions with any project that does not declare a similar upper bound.

This blog post puts forth the argument better than I can about why it is a better practice to omit the upper bound and simply declare `>=3.7`. https://iscinumpy.dev/post/bound-version-constraints/

For more context I ran into this issue a while ago [on my own project](https://github.com/nat-n/poethepoet/issues/43).

I'd be happy to propose a PR if you're convinced.

### Operating System

macOS

### Python Version

3.10

### rstcheck Version

3.5.0

**Comment by Cielquan** [comment]
I read the linked article and some more and I am convinced. Thanks.

A PR would be appreciated. But if you change it in `rstcheck` could also make the change in `rstcheck-core` as well, because otherwise it would be somewhat pointless I guess. No need for a new issue in core, just reference this issue in the PR.

Unfortunately my free time in which I can make a new release is very scarce. Merging PRs I can do from anywhere. The coming weekend is the last opportunities for me to make a new release for the next around 2 months to come.

**Comment by Cielquan** [comment]
This should be fixed in 6.2.0.

Moved from poetry to plain old setuptools with open dependency bounds.
